<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * DestinataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinataireRepository extends EntityRepository
{
}
